# Generated by Django 6.0.3 on 2026-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
